name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang clang-format clang-tidy

      - name: Install Bear
        run: sudo apt-get install -y bear

      - name: Generate Compilation Database with Bear
        run: bear -- make

      - name: Run Clang-Format
        run: |
          find src/ include/ -regex '.*\.\(cpp\|hpp\|h\|cc\|cxx\)' -exec clang-format -style=file -i {} \+
          git diff --exit-code

      - name: Run Clang-Tidy
        run: |
          find src/ include/ -regex '.*\.\(cpp\|hpp\|h\|cc\|cxx\)' -exec clang-tidy {} \+

      - name: Build with Make
        run: make all

      - name: Run tests
        run: make test
